
<Structures>
  <Structure Name="entity" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000000" Description="Xpos" DisplayMethod="signed integer"/>
      <Element Offset="2" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000002" Description="Ypos" DisplayMethod="signed integer"/>
      <Element Offset="4" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000004" Description="tempXpos" DisplayMethod="signed integer"/>
      <Element Offset="6" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000006" Description="tempYpos" DisplayMethod="signed integer"/>
      <Element Offset="8" Vartype="2 Bytes" Bytesize="2" RLECount="6" OffsetHex="00000008" DisplayMethod="signed integer"/>
      <Element Offset="20" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000014" Description="Entity ID" DisplayMethod="signed integer"/>
      <Element Offset="22" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000016" Description="EntitySprite" DisplayMethod="signed integer"/>
      <Element Offset="24" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000018" Description="EntityPatFrame" DisplayMethod="signed integer"/>
      <Element Offset="26" Vartype="2 Bytes" Bytesize="2" RLECount="2" OffsetHex="0000001A" DisplayMethod="signed integer"/>
      <Element Offset="30" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000001E" Description="FrmPatDisp" DisplayMethod="signed integer"/>
      <Element Offset="32" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000020" DisplayMethod="signed integer"/>
      <Element Offset="34" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000022" Description="EntHitXoff" DisplayMethod="signed integer"/>
      <Element Offset="36" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000024" Description="EntHitYoff" DisplayMethod="signed integer"/>
      <Element Offset="38" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000026" Description="Hitbox Width" DisplayMethod="signed integer"/>
      <Element Offset="40" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000028" Description="Hitbox Height" DisplayMethod="signed integer"/>
      <Element Offset="42" Vartype="2 Bytes" Bytesize="2" RLECount="14" OffsetHex="0000002A" DisplayMethod="signed integer"/>
      <Element Offset="70" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000046" Description="Damage" DisplayMethod="signed integer"/>
      <Element Offset="72" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000048" Description="Stun?" DisplayMethod="signed integer"/>
      <Element Offset="74" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000004A" DisplayMethod="signed integer"/>
      <Element Offset="76" Vartype="2 Bytes" Bytesize="2" OffsetHex="0000004C" Description="HitType" DisplayMethod="signed integer"/>
      <Element Offset="78" Vartype="2 Bytes" Bytesize="2" RLECount="11" OffsetHex="0000004E" DisplayMethod="signed integer"/>
      <Element Offset="100" Vartype="2 Bytes" Bytesize="2" OffsetHex="00000064" Description="of interest. saturn 236236a" DisplayMethod="signed integer"/>
      <Element Offset="102" Vartype="2 Bytes" Bytesize="2" RLECount="91" OffsetHex="00000066" DisplayMethod="signed integer"/>
    </Elements>
  </Structure>
</Structures>