
<Structures>
  <Structure Name="vse_pat_entry" AutoFill="0" AutoCreate="1" DefaultHex="0" AutoDestroy="0" DoNotSaveLocal="0" RLECompression="1" AutoCreateStructsize="4096">
    <Elements>
      <Element Offset="0" Vartype="Byte" Bytesize="1" OffsetHex="00000000" Description="Sprite" DisplayMethod="signed integer"/>
      <Element Offset="1" Vartype="Byte" Bytesize="1" OffsetHex="00000001" Description="Duration" DisplayMethod="signed integer"/>
      <Element Offset="2" Vartype="Byte" Bytesize="1" OffsetHex="00000002" Description="Hit1Xoff" DisplayMethod="signed integer"/>
      <Element Offset="3" Vartype="Byte" Bytesize="1" OffsetHex="00000003" Description="Hit1Yoff" DisplayMethod="signed integer"/>
      <Element Offset="4" Vartype="Byte" Bytesize="1" OffsetHex="00000004" Description="Hit1Width" DisplayMethod="signed integer"/>
      <Element Offset="5" Vartype="Byte" Bytesize="1" OffsetHex="00000005" Description="Hit1Height" DisplayMethod="signed integer"/>
      <Element Offset="6" Vartype="Byte" Bytesize="1" OffsetHex="00000006" Description="Hit2Xoff" DisplayMethod="signed integer"/>
      <Element Offset="7" Vartype="Byte" Bytesize="1" OffsetHex="00000007" Description="Hit2Yoff" DisplayMethod="signed integer"/>
      <Element Offset="8" Vartype="Byte" Bytesize="1" OffsetHex="00000008" Description="Hit2Width" DisplayMethod="signed integer"/>
      <Element Offset="9" Vartype="Byte" Bytesize="1" OffsetHex="00000009" Description="Hit2Height" DisplayMethod="signed integer"/>
      <Element Offset="10" Vartype="Byte" Bytesize="1" OffsetHex="0000000A" Description="HurtXoff" DisplayMethod="signed integer"/>
      <Element Offset="11" Vartype="Byte" Bytesize="1" OffsetHex="0000000B" Description="HurtYoff" DisplayMethod="signed integer"/>
      <Element Offset="12" Vartype="Byte" Bytesize="1" OffsetHex="0000000C" Description="HurtWidth" DisplayMethod="signed integer"/>
      <Element Offset="13" Vartype="Byte" Bytesize="1" OffsetHex="0000000D" Description="HurtHeight" DisplayMethod="signed integer"/>
      <Element Offset="14" Vartype="Byte" Bytesize="1" RLECount="4" OffsetHex="0000000E" DisplayMethod="signed integer"/>
      <Element Offset="18" Vartype="Byte" Bytesize="1" OffsetHex="00000012" Description="CollisionWidth" DisplayMethod="signed integer"/>
      <Element Offset="19" Vartype="Byte" Bytesize="1" OffsetHex="00000013" Description="CollisionHeight" DisplayMethod="signed integer"/>
      <Element Offset="20" Vartype="Byte" Bytesize="1" OffsetHex="00000014" Description="DamageDealt" DisplayMethod="signed integer"/>
      <Element Offset="21" Vartype="Byte" Bytesize="1" OffsetHex="00000015" Description="StunDealt" DisplayMethod="signed integer"/>
      <Element Offset="22" Vartype="Byte" Bytesize="1" OffsetHex="00000016" Description="blockType" DisplayMethod="signed integer"/>
      <Element Offset="23" Vartype="Byte" Bytesize="1" OffsetHex="00000017" Description="HitType" DisplayMethod="signed integer"/>
      <Element Offset="24" Vartype="Byte" Bytesize="1" OffsetHex="00000018" DisplayMethod="signed integer"/>
      <Element Offset="25" Vartype="Byte" Bytesize="1" OffsetHex="00000019" Description="Sfx1" DisplayMethod="signed integer"/>
      <Element Offset="26" Vartype="Byte" Bytesize="1" OffsetHex="0000001A" Description="Sfx2" DisplayMethod="signed integer"/>
      <Element Offset="27" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="0000001B" DisplayMethod="signed integer"/>
      <Element Offset="29" Vartype="Byte" Bytesize="1" OffsetHex="0000001D" Description="actionEntityRelated" DisplayMethod="signed integer"/>
      <Element Offset="30" Vartype="Byte" Bytesize="1" RLECount="2" OffsetHex="0000001E" DisplayMethod="signed integer"/>
      <Element Offset="32" Vartype="Byte" Bytesize="1" OffsetHex="00000020" Description="clashXoff" DisplayMethod="signed integer"/>
      <Element Offset="33" Vartype="Byte" Bytesize="1" OffsetHex="00000021" Description="clashYoff" DisplayMethod="signed integer"/>
      <Element Offset="34" Vartype="Byte" Bytesize="1" OffsetHex="00000022" Description="clashWidth" DisplayMethod="signed integer"/>
      <Element Offset="35" Vartype="Byte" Bytesize="1" OffsetHex="00000023" Description="clashHeight" DisplayMethod="signed integer"/>
      <Element Offset="36" Vartype="Byte" Bytesize="1" RLECount="9" OffsetHex="00000024" DisplayMethod="signed integer"/>
    </Elements>
  </Structure>
</Structures>